config/routes.rb
Rails.application.routes.draw do
  #get 'home/zipcode'

  root 'home#index'

  post 'zipcode' => 'home#zipcode'

  get 'home/zipcode'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
 class HomeController < ApplicationController
  def index
    require 'net/http'
    require 'json'
    @url = 'https://www.airnowapi.org/aq/observation/zipCode/current/?format=application/json&zipCode=89129&distance=0&API_KEY=B216E8FC-0AD9-4BEF-B411-CC4BC3E8A50C' 
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @output = JSON.parse(@response)


      #Error checking for empty output
      if @output.empty?
        @final_output = "Output Error"
      else
        @final_output = @output[0]['AQI']
      end

    if @final_output == "Error"
      @api_color = "red"
    elsif @final_output <= 50
      @api_color = "green"
      @api_description = "This number is considered good"
    elsif @final_output >= 51 && @final_output <=100
      @api_color = "yellow"
      @api_description = "This number is considered moderate"
    elsif @final_output >= 101 && @final_output <=150
      @api_color = "orange"
      @api_description = "This number is considered unhealthy for Sensitive Groups (USG)"
    elsif @final_output >= 151 && @final_output <=200
      @api_color = "red"
      @api_description = "This number is considered unhealthy"
    elsif @final_output >= 201 && @final_output <=300
      @api_color = "purple"
      @api_description = "This number is considered very unhealthy"
    elsif @final_output >= 301 && @final_output <=500
      @api_color = "maroon"
      @api_description = "This number is considered hazardous"
      end   
  end
  
  def zipcode
    @zip_query = params[:zipcode]

    if params[:zipcode] == ""
      @zip_query = "Please enter a valid zipcode"
    elsif params[:zipcode]

      require 'net/http'
      require 'json'
      @url = 'https://www.airnowapi.org/aq/observation/zipCode/current/?format=application/json&zipCode=' + @zip_query.to_s + '&distance=0&API_KEY=B216E8FC-0AD9-4BEF-B411-CC4BC3E8A50C' 
      @uri = URI(@url)
      @response = Net::HTTP.get(@uri)
      @output = JSON.parse(@response)


          #Error checking for empty output
          if @output.empty?
        @final_output = "Output Error"
      else
        @final_output = @output[0]['AQI']
      end

    if @final_output == "Error"
      @api_color = "red"
    elsif @final_output <= 50
      @api_color = "green"
      @api_description = "This number is considered good"
    elsif @final_output >= 51 && @final_output <=100
      @api_color = "yellow"
      @api_description = "This number is considered moderate"
    elsif @final_output >= 101 && @final_output <=150
      @api_color = "orange"
      @api_description = "This number is considered unhealthy for Sensitive Groups (USG)"
    elsif @final_output >= 151 && @final_output <=200
      @api_color = "red"
      @api_description = "This number is considered unhealthy"
    elsif @final_output >= 201 && @final_output <=300
      @api_color = "purple"
      @api_description = "This number is considered very unhealthy"
    elsif @final_output >= 301 && @final_output <=500
      @api_color = "maroon"
      @api_description = "This number is considered hazardous"
      end 
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Ozone", root_path, class:"navbar-toggler" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>

        
      </ul>
      <%= form_tag zipcode_path, :method => 'POST' do %>
      <div class="d-flex">
        <%= text_field_tag 'zipcode', nil, placeholder: "search zipcode", class: "form-control me-2" %>

        <%= submit_tag 'Search', class: 'btn btn-outline-success' %>

        <!-- <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"> !-->

        
        <% end %>
      </form>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<div class="card <%= @api_color %>" style="width: 18rem;">
  <img src="https://i.imgur.com/o1e9atI.jpeg" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title"><%= @final_output %></h5>
    <p class="card-text">This is the current Ozone air quality read-out for my neighborhood in Las Vegas</p>
    <hr class="my-4">
    <p><%= @api_description %><p/>
    <p>Reload your browser to update the read-out!<p/>
    
  </div>
</div>

<br/>


<br/> </br>

app/views/home/zipcode.html.erb
<div class="card <%= @api_color %>" style="width: 18rem;">
  <img src="https://i.imgur.com/o1e9atI.jpeg" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title"><%= @final_output %></h5>
    <p class="card-text">This is the current Ozone air quality read-out for my neighborhood in Las Vegas</p>
    <hr class="my-4">
    <p><%= @api_description %><p/>
    <p>Reload your browser to update the read-out!<p/>
  </div>
</div>

<br/>


<br/> </br>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <%= render 'home/navbar' %>

    <title>OZONE</title>

      <meta name="viewport" content="width=device-width,initial-scale=1">
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  <body>

    

    <div class="container">
      <br/>
      <%= yield %>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>
    -->
  </body>
</html>